### ISSUE TITLE
DMG broken

### ISSUE THREAD

**Issue by qbatten** [pkamenarsky/atea#34]
The he downloadable .dmg (at https://github.com/downloads/pkamenarsky/atea/atea-1.0.3.dmg) won't open on my computer. I suspect it's the "JavaApplicationStub" file that's causing the problem. When I try to open the program it says it's damaged and tells me to eject the disk image." Same thing happens with the application copied over to my Applications folder. I am not particularly tech-savvy but would love to use this app if this is an easy fix! 

I'm running Mac OSX 10.11.4 on an Intel i5 and have the most recent update to Java, if that information is at all helpful.

Many thanks for your work on this, it looks like  great tool.

**Comment by pkamenarsky** [comment]
Sorry for the late reply!

I'll have to look more into that, but for now a quick workaround would be to start Atea from the terminal. I.e. if you installed it in `/Applications`, start up a terminal and type:

    /Applications/atea.app/Contents/MacOS/JavaApplicationStub &

**Comment by qbatten** [comment]
No worries, and thank you very much! When I launch from Terminal, I get a bunch of errors, which I've added below, in case they're helpful. It looks like the application pretty much works, though.

Messages:
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const: conn 0x24bff token 0x3ffffffffffd0a
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: Backtrace (at 217075):
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff9f71cb98 CGSDisableUpdateToken + 155
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff954c5524 ___disable_updates_sync_block_invoke_2 + 17
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x00007fff9644e40b _dispatch_client_callout + 8
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x00007fff9644f9f2 _dispatch_barrier_sync_f_invoke + 74
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  4   AppKit                              0x00007fff954c53f2 NSCGSDisableUpdates + 213
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  5   AppKit                              0x00007fff954c5228 NSCGSTransactionRunPreCommitActionsForOrder_ + 156
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x00007fff954c516f NSCGSTransactionRunPreCommitActions_ + 21
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x00007fff954a71e3 -[_NSCGSTransaction addActionWithOrder:usingBlock:] + 220
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x00007fff954a70f7 NSCGSTransactionAddAction + 68
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x00007fff954a7519 NSCGSWindowMark_ + 263
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x00007fff954a737f -[_NSCGSWindow setFrame:] + 369
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x00007fff9552f022 _NXCreateWindowWithStyleMask + 157
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x00007fff9552ee9e _NSCreateWindow + 184
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x00007fff9557b7c4 -[NSWindow _commonAwake] + 1516
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x00007fff9538cb73 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 815
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x00007fff9538b0c7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1475
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x00007fff9538aafd -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x00007fff95a53ae2 -[NSStatusBarWindow initWithContentRect:] + 89
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  18  AppKit                              0x00007fff95a4ff2c -[NSStatusBar(NSStatusBar_Appearance) _createStatusItemWindow] + 124
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  19  AppKit                              0x00007fff95a56622 -[NSStatusItem _initInStatusBar:withLength:withPriority:hidden:] + 453
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  20  AppKit                              0x00007fff95a5641b +[NSStatusItem _itemInStatusBar:withLength:withPriority:] + 80
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  21  libtray.jnilib                      0x000000010ee8791e -[StatusItemWrapper installStatusItem] + 233
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  22  libtray.jnilib                      0x000000010ee87037 Java_org_jdesktop_jdic_tray_internal_impl_MacTrayIconService_createStatusItem + 148
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  23  ???                                 0x0000000108515eee 0x0 + 4434517742
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  24  ???                                 0x000000010850a929 0x0 + 4434471209
Mar 14 10:26:27  JavaApplicationStub[10191] <Warning>: void CGSUpdateManager::log() const:  25  ???                                 0x000000010850a85a 0x0 + 4434471002

**Comment by dmitrym0** [comment]
This no longer works on macOS 10.12.6:

```
/A/a/C/MacOS ❯❯❯ ./JavaApplicationStub
[JavaAppLauncher Error] CallStaticVoidMethod() threw an exception
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Launcher
	at apple.launcher.LaunchRunner.loadMainMethod(LaunchRunner.java:56)
	at apple.launcher.LaunchRunner.run(LaunchRunner.java:112)
	at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
	at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
```


```
/A/a/C/MacOS ❯❯❯ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

```

**Comment by velaia** [comment]
> /Applications/atea.app/Contents/MacOS/JavaApplicationStub &

Worked for me under macOS 10.14.3 (18D109) with the [Java 6 compatibility package](https://support.apple.com/kb/DL1572?locale=en_US) installed.

![image](https://user-images.githubusercontent.com/1515904/54612225-83006580-4a93-11e9-89a1-7d78f1120119.png)
